app_settings:
  auto_launch_browser: True
  server_name: "0.0.0.0"
  server_port: 7862
blender_settings:
  clean_frames: True
  frame_fixer_depth: 10
  frame_rate: 30
  gif_duration: 1000
  max_frame_rate: 1000
  projects_file: "video_blender_projects.csv"
  skip_frames: 100
directories:
  output_blender: "output/blender"
  output_deduplication: "output/deduplication"
  output_fps_change: "output/fps_change"
  output_gif_to_mp4: "output/gif_to_mp4"
  output_inflation: "output/inflation"
  output_interpolation: "output/interpolation"
  output_restoration: "output/restoration"
  output_resynthesis: "output/resynthesis"
  output_search: "output/search"
  output_upscaling: "output/upscaling"
  working: "temp"
deduplicate_settings:
  default_precision: 10
  default_threshold: 2500
  default_tuning_step: 100
  max_dupes_per_group: 0
  max_lines: 40
  max_max_dupes: 1000
  max_precision: 60
  max_tuning_rows: None
  max_threshold: 25000
  max_tuning_step: 10000
  min_threshold: 0
  min_tuning_step: 0
  threshold_step: 100
  tuning_step_step: 10
engine_settings:
  gpu_ids: "0"
  model: "ours"
  use_time_step: False
enhance_images_settings:
  threshold_min: 1
  threshold_max: 50
  threshold_step: 0.25
  threshold_default: 2
ffmpeg_settings:
  global_options: "-hide_banner -loglevel error -nostats"
fps_change_settings:
  default_precision: 10
  ending_fps: 30
  max_precision: 60
  maximum_fps: 1024
  starting_fps: 25
gif_to_mp4_settings:
  default_crf: 23
  frame_rate: 30
  file_types:
  - "avi"
  - "flv"
  - "gif"
  - "m4v"
  - "mov"
  - "mp4"
  - "mpeg"
  - "mpg"
  - "qt"
  - "webm"
  - "wmv"
  maximum_crf: 28
  max_frame_rate: 1000
  minimum_crf: 17
  resampling_precision: 10
  use_tiling: False
interpolation_settings:
  create_gif: True
  create_zip: True
  create_txt: True
  gif_duration: 3000
  max_splits: 10
logviewer_settings:
  max_lines: 25
mp4_to_png_settings:
  frame_rate: 30
  max_frame_rate: 1000
png_to_gif_settings:
  frame_rate: 30
  max_frame_rate: 1000
png_to_mp4_settings:
  default_crf: 23
  frame_rate: 30
  max_frame_rate: 1000
  maximum_crf: 28
  minimum_crf: 17
realesrgan_settings:
  fp32: True
  gpu_ids: "0"
  model_name: "RealESRGAN_x4plus"
  tile_pad: 10
  tiling: 256
remixer_settings:
  backup_split_scenes: True
  custom_ffmpeg_video: -c:v libx264 -crf 23
  custom_ffmpeg_audio: -c:a aac -shortest
  default_crf: 23
  def_project_fps: 29.97
  default_gif_fps: 10
  file_types:
  - "avi"
  - "flv"
  - "gif"
  - "m4v"
  - "mov"
  - "mp4"
  - "mpeg"
  - "mpg"
  - "qt"
  - "webm"
  - "wmv"
  gif_end_delay: 1.0
  gif_factor: 10
  labeled_ffmpeg_video: -vf "drawtext=<LABEL>" -c:v libx264 -crf <CRF>
  labeled_ffmpeg_audio: -c:a aac -shortest
  marked_border_size: 5
  marked_box_color: "#000000@0.5"
  marked_draw_box: True
  marked_draw_shadow: False
  marked_ffmpeg_video: -vf "drawtext=<LABEL>" -c:v libx264 -crf 28
  marked_ffmpeg_audio: -c:a aac -shortest
  marked_font_color: "#FFFFFF@0.9"
  marked_font_size: 30
  marked_font_file: fonts/trim.ttf
  marked_position_v: "Top"
  marked_position_h: "Center"
  marked_shadow_size: 20
  marked_shadow_color: "#000000@0.9"
  max_project_fps: 60.0
  max_thumb_size: 512
  maximum_crf: 28
  min_frames_per_scene: 10
  minimum_crf: 17
  raise_on_error: False
  scale_type_up: "lanczos"
  scale_type_down: "area"
  source_audio_crf: 28
  thumb_scale: 0.5
  use_tiling_over: 921600
restoration_settings:
  create_gif: True
  create_zip: True
  create_txt: True
  default_frames: 2
  default_precision: 10
  gif_duration: 1000
  max_frames: 10
  max_precision: 60
search_settings:
  default_splits: 10
  max_splits: 60
slice_settings:
  default_crf: 28
  default_gif_fps: 10
  def_scale_factor: 0.5
  frame_rate: 30
  gif_end_delay: 1.0
  gif_factor: 10
  gif_high_quality: False
  max_frame_rate: 1000
  maximum_crf: 28
  maximum_gif_fps: 60
  max_scale_factor: 1.0
  minimum_crf: 17
upscale_settings:
  file_types:
  - "bmp"
  - "gif"
  - "png"
  - "jfif"
  - "jpe"
  - "jpeg"
  - "jpg"
user_interface:
  css_file: "webui.css"
  log_file: None
  mtqdm_use_color: True
  mtqdm_palette: "default"
  resources_path: "resources.csv"
  show_header: True
  theme: "default"
  tips_path: "guide"
